### ISSUE TITLE
unable to push kernel to the target hardware

### ISSUE THREAD

**Issue by bitkis** [RusPiRo/ruspiro-loader#5]
Using https://github.com/RusPiRo/ruspiro-loader/tree/fix/update_dependencies and #4: 

` screen /dev/tty.usbserial-AR0JXMSY 115200`
```
########## RusPiRo ---------- Bootloader v1.0 ---------- ##########
prepare boot loader
waiting for a new kernel...
```

`cargo ruspiro-push -k ./target/kernel8.img -p /dev/tty.usbserial-AR0JXMSY`
```
Kernel file to send: ./target/kernel8.img with mode aarch64
Send to port: /dev/tty.usbserial-AR0JXMSY
Send kernel to device. Initiate with token...
unable to push kernel to the target hardware
```

**Comment by bitkis** [comment]
mind if I implement XMODEM receive on rPi side? Then we should be able to get rid of ruspiro-push and do file transfers from within of a terminal emulator?

**Comment by 2ndTaleStudio** [comment]
I‘ve only used the push from a windows machine. I‘ll try to test on a spare Mac as well. However, if you get another transfer protocol implemented on the baremetal bootloader this would be appreciated. Another option would be to make the current transfer mor stable and reliable? The cargo ruspiro-push target was to provide cross platform transfer being easy to use from within the Makefile.toml - but any enhancement would be welcome. On my Windows machine it works rather smooth 🤷

**Comment by bitkis** [comment]
Just in case there is a misunderstanding --

I see the advantages of using xmodem instead of the homegrown protocol as:
1. Being able to send data from within of a terminal emulator, enabling bi-directional communication and avoiding risk of missing early output.
2. Send data using "standard" system utilities or functionality built into a terminal emulator.

I think I will try to figure out the issue I observe separately -- need to get at least something working.

> On my Windows machine it works rather smooth

Are you able to build ruspiro-loader without applying #4 on Windows??

**Comment by bitkis** [comment]
> I think I will try to figure out the issue I observe separately -- need to get at least something working.

Fixed in https://github.com/RusPiRo/ruspiro-push/pull/1
